<!-- auto-generated by QWER -->
<script lang="ts">
  /* eslint-disable @typescript-eslint/ban-ts-comment */
  // @ts-nocheck
  import Post from '$lib/layouts/post.svelte';
  import ImgZoom from '$lib/components/image_zoom.svelte';
  import Video from '$lib/components/video.svelte';
  import CodeCopy from '$lib/components/code_copy.svelte';
  import InfoBox from '$lib/components/info_box.svelte';
</script>

<Post>
  <article slot="post_content">
    <h2 id="intro"><a href="#intro">✨ Intro</a></h2>
    <p>
      <a href="https://www.github.com/kwchang0831/svelte-QWER" rel="external">QWER</a>
      is simply an Awesoem blog starter and static site generator. Built using
      <a href="https://kit.svelte.dev/" rel="external">SvelteKit</a>
      and Love ❤.
    </p>
    <h2 id="try-out-qwer"><a href="#try-out-qwer">🎉 Try out QWER</a></h2>
    <p>
      Create a QWER blog named <code class="inline-code-block">my-blog</code>
      .
    </p>
    <div class="code-block  ">
      <CodeCopy>
        <pre><code
            class="language-sh">{@html String.raw`<div class="code-line"><div class="code-linenotation"><span class="no-line-number"></span><span class="no-line-diff"></span></div><div class="code-content">npx degit kwchang0831/svelte-QWER my-blog</div></div>`}</code></pre>
      </CodeCopy>
    </div>
    <h2 id="to-dev"><a href="#to-dev">⚡️ To Dev</a></h2>
    <ol>
      <li>
        <p>Install all the dependencies.</p>
        <div class="code-block  ">
          <CodeCopy>
            <pre><code
                class="language-sh">{@html String.raw`<div class="code-line"><div class="code-linenotation"><span class="no-line-number"></span><span class="no-line-diff"></span></div><div class="code-content"><span class="token function">pnpm</span> i</div></div>`}</code></pre>
          </CodeCopy>
        </div>
      </li>
      <li>
        <p>Start local dev server.</p>
        <div class="code-block  ">
          <CodeCopy>
            <pre><code
                class="language-sh">{@html String.raw`<div class="code-line"><div class="code-linenotation"><span class="no-line-number"></span><span class="no-line-diff"></span></div><div class="code-content"><span class="token function">pnpm</span> dev</div></div>`}</code></pre>
          </CodeCopy>
        </div>
      </li>
      <li>
        <p>Sever is running. Open browser to see the result.</p>
        <div class="code-block  ">
          <CodeCopy>
            <pre><code
                class="language-sh">{@html String.raw`<div class="code-line"><div class="code-linenotation"><span class="no-line-number"></span><span class="no-line-diff"></span></div><div class="code-content">VITE v3.1.1  ready <span class="token keyword">in</span> <span class="token number">1080</span> ms</div></div><div class="code-line"><div class="code-linenotation"><span class="no-line-number"></span><span class="no-line-diff"></span></div><div class="code-content"></div></div><div class="code-line"><div class="code-linenotation"><span class="no-line-number"></span><span class="no-line-diff"></span></div><div class="code-content">➜  Local:   http://localhost:5173/</div></div><div class="code-line"><div class="code-linenotation"><span class="no-line-number"></span><span class="no-line-diff"></span></div><div class="code-content">➜  Network: use <span class="token parameter variable">--host</span> to expose</div></div>`}</code></pre>
          </CodeCopy>
        </div>
      </li>
    </ol>
    <h2 id="to-deploy"><a href="#to-deploy">🚀 To Deploy</a></h2>
    <ol>
      <li>
        <p>
          Create a free <a href="https://vercel.com/" rel="external">Vercel</a>
          account.
        </p>
      </li>
      <li>
        <p>Install Vercel CLI</p>
        <div class="code-block  ">
          <CodeCopy>
            <pre><code
                class="language-sh">{@html String.raw`<div class="code-line"><div class="code-linenotation"><span class="no-line-number"></span><span class="no-line-diff"></span></div><div class="code-content"><span class="token function">npm</span> i <span class="token parameter variable">-g</span> vercel</div></div>`}</code></pre>
          </CodeCopy>
        </div>
      </li>
      <li>
        <p>Using the vercel command from the root of a project directory.</p>
        <div class="code-block  ">
          <CodeCopy>
            <pre><code
                class="language-sh">{@html String.raw`<div class="code-line"><div class="code-linenotation"><span class="no-line-number"></span><span class="no-line-diff"></span></div><div class="code-content">vercel</div></div>`}</code></pre>
          </CodeCopy>
        </div>
        <p>You will be asked to login for the first time. Simply follow the prompts.</p>
      </li>
      <li>
        <p>Deploy as Production build</p>
        <div class="code-block  ">
          <CodeCopy>
            <pre><code
                class="language-sh">{@html String.raw`<div class="code-line"><div class="code-linenotation"><span class="no-line-number"></span><span class="no-line-diff"></span></div><div class="code-content">vercel deploy <span class="token parameter variable">--prod</span></div></div>`}</code></pre>
          </CodeCopy>
        </div>
      </li>
    </ol>
    <h2 id="learn-more"><a href="#learn-more">📚 Learn More</a></h2>
    <p>
      Here is our Documentation: <a href="https://docs-svelte-qwer.vercel.app/" rel="external">
        https://docs-svelte-qwer.vercel.app/
      </a>
      .
    </p>
    <h2 id="end"><a href="#end">👍 END</a></h2>
  </article>
</Post>
