export const Config = {
  StaticFolder: 'static',
  BuildFolder: 'build',
  UserPublicFolder: 'user/public',
  UserDataFolder: 'user/data',
  UserAssetsFolder: 'user/assets',
  RouteFolder: 'src/routes',
  PreserveFilesInRoutes: [
    'src/routes/+error.svelte',
    'src/routes/+layout.svelte',
    'src/routes/+page.svelte',
    'src/routes/atom.xml/+server.ts',
    'src/routes/feed.json/+server.ts',
    'src/routes/manifest.webmanifest/+server.ts',
    'src/routes/sitemap.xml/+server.ts',
    'src/routes/robots.txt/+server.ts',
  ],
  TemplateFolder: 'src/lib/template',
  GeneratedFolder: 'src/generated',
  AssetsFolder: 'src/generated/assets',
  PostsJsonPath: 'src/generated/posts.json',
  TagsJsonPath: 'src/generated/tags.json',
  AssetsJsonPath: 'src/generated/assets.json',
  AssetsStorePath: 'src/generated/assets.ts',
  AssetStoreTemplatePath: '_assets.ts',
  PrefixGeneratedFileTemplate: /^<!-- auto-generated by QWER -->$/,
  DefaultLayout: '_article.svelte',
  DefaultLayoutTemplateStr_Content: /<!-- :QWER CONTENT: -->/,
  DefaultLayoutTemplateStr_Imports: /\/\*<!-- :QWER IMPORTS: -->\*\//,
  DefaultCoverStyle: 'IN',
  DefaultTagName: 'tags',
  PostLanguageTagName: 'Language',
  DefaultPostLanguage: 'English',
  SeriesTagName: 'Series',
  YearTagName: 'Year',
};

export const ImageConfig = {
  SupportedImageFormat: ['avif', 'png', 'jpg', 'jpeg', 'heif', 'heic', 'tiff', 'gif', 'webp'],
  SupportedVideoFormat: ['webm', 'mp4'],

  AssetTypePath: 'src/generated/asset.d.ts',
  AssetTypeTemplatePath: '_asset.d.ts',

  PrefixImageTypeTemplate: /\/\*<!-- :QWER ImageResolutions: -->\*\//,
  AssetTemplateStr_Import: /\/\*<!-- :QWER IMPORTS: -->\*\//,
  AssetTemplateStr_MapData: /\/\*<!-- :QWER MAPDATA: -->\*\//,
  OriginalImageFolder: '$generated/assets',
  BannerImage: {
    width: 900,
    height: 200,
    format: ['avif'],
  },
  ExtraResolutions: {
    1280: {
      width: 1280,
      format: ['avif'],
      minWidth: '1024px',
    },
    800: {
      width: 800,
      format: ['avif'],
      minWidth: '360px',
    },
  },
  // For original image without reszing
  ExtraFormats: ['avif'],
};
