export const Config = {
  StaticFolder: 'static',
  BuildFolder: 'build',
  PublicFolder: 'public',
  DataFolder: 'data',
  RouteFolder: 'src/routes',
  PreserveFilesInRoutes: ['src/routes/__error.svelte', 'src/routes/__layout.svelte', 'src/routes/index.svelte'],
  TemplateFolder: 'src/lib/template',
  GeneratedFolder: 'src/generated',
  AssetsFolder: 'src/generated/assets',
  PostsJsonPath: 'src/generated/posts.json',
  TagsJsonPath: 'src/generated/tags.json',
  AssetsStorePath: 'src/generated/assets.ts',
  AssetStoreTemplatePath: '_assets.ts',
  PrefixGeneratedFileTemplate: /^<!-- auto-generated by QWER -->$/,
  DefaultLayout: '_article.svelte',
  DefaultCoverStyle: 'IN',
  DefaultTagName: 'tags',
};

export const ImageConfig = {
  SupportedImageFormat: ['avif', 'png', 'jpg', 'jpeg', 'heif', 'heic', 'tiff', 'gif', 'webp'],
  SupportedVideoFormat: ['webm', 'mp4'],

  AssetTypePath: 'src/generated/asset.d.ts',
  AssetTypeTemplatePath: '_asset.d.ts',

  PrefixImageTypeTemplate: /\/\*<!-- :QWER ImageResolutions: -->\*\//,
  OriginalImageFolder: '$generated/assets',
  BannerImage: {
    width: 900,
    height: 200,
    format: ['avif', 'webp'],
  },
  ExtraResolutions: {
    1280: {
      width: 1280,
      format: ['avif', 'webp'],
      minWidth: '1280px',
    },
    1024: {
      width: 1024,
      format: ['avif', 'webp'],
      minWidth: '1024px',
    },
    854: {
      width: 854,
      format: ['avif', 'webp'],
      minWidth: '768px',
    },
    640: {
      width: 640,
      format: ['avif', 'webp'],
      minWidth: '360px',
    },
  },
};
