export const Config = {
  StaticFolder: 'static',
  BuildFolder: 'build',
  PublicFolder: 'public',
  DataFolder: 'data',
  RouteFolder: 'src/routes',
  PreserveFilesInRoutes: [
    'src/routes/+error.svelte',
    'src/routes/+layout.svelte',
    'src/routes/+page.svelte',
    'src/routes/atom.xml/+server.ts',
    'src/routes/feed.json/+server.ts',
    'src/routes/manifest.webmanifest/+server.ts',
    'src/routes/sitemap.xml/+server.ts',
    'src/routes/robots.txt/+server.ts',
  ],
  TemplateFolder: 'src/lib/template',
  GeneratedFolder: 'src/generated',
  AssetsFolder: 'src/generated/assets',
  PostsJsonPath: 'src/generated/posts.json',
  TagsJsonPath: 'src/generated/tags.json',
  AssetsJsonPath: 'src/generated/assets.json',
  AssetsStorePath: 'src/generated/assets.ts',
  AssetStoreTemplatePath: '_assets.ts',
  PrefixGeneratedFileTemplate: /^<!-- auto-generated by QWER -->$/,
  DefaultLayout: '_article.svelte',
  DefaultLayoutTemplateStr_Content: /<!-- :QWER CONTENT: -->/,
  DefaultLayoutTemplateStr_Imports: /\/\*<!-- :QWER IMPORTS: -->\*\//,
  DefaultCoverStyle: 'IN',
  DefaultTagName: 'tags',
};

export const ImageConfig = {
  SupportedImageFormat: ['avif', 'png', 'jpg', 'jpeg', 'heif', 'heic', 'tiff', 'gif', 'webp'],
  SupportedVideoFormat: ['webm', 'mp4'],

  AssetTypePath: 'src/generated/asset.d.ts',
  AssetTypeTemplatePath: '_asset.d.ts',

  PrefixImageTypeTemplate: /\/\*<!-- :QWER ImageResolutions: -->\*\//,
  AssetTemplateStr_Import: /\/\*<!-- :QWER IMPORTS: -->\*\//,
  AssetTemplateStr_MapData: /\/\*<!-- :QWER MAPDATA: -->\*\//,
  OriginalImageFolder: '$generated/assets',
  BannerImage: {
    width: 900,
    height: 200,
    format: ['avif', 'webp'],
  },
  ExtraResolutions: {
    1280: {
      width: 1280,
      format: ['avif', 'webp'],
      minWidth: '1280px',
    },
    1024: {
      width: 1024,
      format: ['avif', 'webp'],
      minWidth: '1024px',
    },
    854: {
      width: 854,
      format: ['avif', 'webp'],
      minWidth: '768px',
    },
    640: {
      width: 640,
      format: ['avif', 'webp'],
      minWidth: '360px',
    },
  },
};
