<!-- auto-generated by QWER -->
<script lang="ts">
  import Post from '$lib/layouts/post.svelte';
  import ImgZ from '$lib/components/image_zoom.svelte';
  import Video from '$lib/components/video.svelte';

  /*<!-- :QWER IMPORTS: -->*/
</script>

<Post>
  <article slot="post_content">
    <!-- :QWER CONTENT: -->
  </article>
</Post>
