<!-- auto-generated by QWER -->
<script lang="ts">
  // @ts-nocheck
  import Post from '$lib/layouts/post.svelte';
  import PostHeading from '$lib/components/post_heading.svelte';
  /*<!-- :QWER IMPORTS: -->*/
</script>

<Post>
  <PostHeading slot="post_heading" title="<!-- :QWER POST_TITLE: -->" published="<!-- :QWER POST_PUBLISHED: -->">
    <picture slot="cover">
      <!-- svelte-ignore missing-declaration -->
      <img
        class="w-full h-auto object-cover md:(rounded-2xl shadow-xl)"
        src={Cover}
        alt="https://svelte-qwer.vercel.app/p/2/cover.webp" />
    </picture>
    <p slot="cover_caption">
      <!-- :QWER POST_COVER_CAPTION: -->
    </p>
  </PostHeading>
  <article slot="post_content">
    <!-- :QWER CONTENT: -->
  </article>
</Post>
