<!-- auto-generated by QWER -->
<script lang="ts" context="module">
  // export const prerender = true;
</script>

<script lang="ts">
  import Post from '$lib/layouts/post.svelte';
  /*<!-- :QWER IMPORTS: -->*/
</script>

<Post>
  <article slot="post_content">
    <!-- :QWER CONTENT: -->
  </article>
</Post>
